# Generated by Django 5.2.6 on 2025-10-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_student_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.jpeg', null=True, upload_to='profile_images/'),
        ),
    ]
