# Generated by Django 5.2.6 on 2025-10-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userprofile_usertrustbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='trust_score',
        ),
    ]
