# Generated by Django 5.2.6 on 2025-10-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_userprofile_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_verified_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
