# Generated by Django 5.2.6 on 2025-10-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_student_is_verified_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_verified_by_admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_sales',
        ),
    ]
