# Generated by Django 5.2.6 on 2025-11-06 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_student_is_verified_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertrustbadge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertrustbadge',
            name='product',
        ),
        migrations.RemoveField(
            model_name='usertrustbadge',
            name='rated_user',
        ),
        migrations.RemoveField(
            model_name='usertrustbadge',
            name='rater',
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserTrustBadge',
        ),
    ]
