# Generated by Django 5.2.6 on 2025-11-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
