# Generated by Django 5.2.6 on 2025-11-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productsaletransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
    ]
