# Generated by Django 5.2.6 on 2025-11-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
