# Generated by Django 5.2.6 on 2025-11-13 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_available_product_is_sold'),
        ('products', '0008_product_manufacture_date'),
    ]

    operations = [
    ]
